version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/backend/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/frontend/'
    schedule:
      interval: 'weekly'
